### PR TITLE
Improve canvas zoom

### PR DESCRIPTION
**Pull request by Alecaddd**
## Summary / How this PR fixes the problem?
Improve the various zoom interactions to offer a better user experience.

## Steps to Test
1. Zoom with the <kbd>CTRL</kbd> + scroll
2. Zoom with <kbd>CTRL</kbd> + <kbd>+</kbd> or <kbd>-</kbd>
3. Zoom with the HeaderBar buttons.

## Screenshots 
TBD

## This PR fixes/implements the following **bugs/features**:
- Zoom by 10% when using the keyboard shortcut.
- Zoom by 50% when using the HeaderBar button.
- Zoom by delta variation when using the mouse scroll.

### CODE REVIEW

**Comment by Alecaddd** [comment]
@isneezy would you be willing to give this PR a review, since you've been very active lately and you worked on some aspects of the zoom architecture?

**Review by isneezy — COMMENTED** [review]
@Alecaddd  I see you have prevented the canvas from shrink below 2% which is great and almost everything looks fine to me.
What bothers me is the fact that when you zoom out to 2% and then zoom in again it goes like by 12%, 22%, etc. IDK if we want to keep it like this or do some kind of correction.

**Comment by Alecaddd** [comment]
@isneezy that's the tricky part of zooming with the mouse, as it always returns a delta of 1 or -1, so I'm dividing it by 10 to prevent zooming in an out by 100%.
Scrolling with a trackpad is more natural as it actually returns the real acceleration.
I'm not sure if there's a method to get the proper delta acceleration of the mouse wheel.

**Comment by Alecaddd** [comment]
Fixed!

**Pull request merged**
