### PR TITLE
Github Actions: add flatpak

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by Alecaddd** [comment]
Is this good to go?
Feel free to merge it if it works :smile:

**Comment by Alecaddd** [comment]
@bilelmoussaoui is this good to go?

**Comment by bilelmoussaoui** [comment]
I still need to clean the github action first as we do ask for a bit more than we need during the build. I'm working on that upstream already

**Comment by Wetrain** [comment]
Is there anything i can do to help with this?

**Comment by bilelmoussaoui** [comment]
> Is there anything i can do to help with this?

I just need to figure out how to make it use the [github action ](https://github.com/bilelmoussaoui/flatpak-github-actions); Github Actions don't allow setting any config when running the docker container.  

I will give it an other shot this weekend & will let you know! Thanks Adam :)

**Comment by albfan** [comment]
@bilelmoussaoui I'm running this locally but it says:

```
MANIFEST must be specified
Usage:
  flatpak-builder [OPTION?] DIRECTORY MANIFEST - Build manifest
```

Any ideas of what is going on? I will take a look to bilelmoussaoui/flatpak-github-actions:latest now

**Comment by Alecaddd** [comment]
We're very close from releasing an alpha, we only need to fix a couple of methods.
What's the status on this PR?

**Comment by bilelmoussaoui** [comment]
The merge request should be closed as the Github action can't work really, it requires a privileged container and I couldn't find a way to make it work so far :/ 
I'm still hoping for some changes on Github Actions to give us more flexibility in that regards

**Comment by Alecaddd** [comment]
All right, that's too bad.
Thanks for the udpate

**Pull request closed without merging**
