### PR TITLE
Add Arabic Support

### PR DESCRIPTION
**Pull request by ashraf2033**
I've added Arabic language support by editing ar.po file with poedit.

## Summary / How this PR fixes the problem?
It adds initial Arabic translations for the current strings available in the code

## Steps to Test
I wanted to test but my OS is English and I don't have time to change local, I hope there was another way to test through editing the code.
## Screenshots 
N/A
## Known Issues / Things To Do
N/A
## This PR fixes/implements the following **bugs/features**:
N/A

### CODE REVIEW

**Comment by Alecaddd** [comment]
What's the `po/ar.mo` file?

**Comment by ashraf2033** [comment]
I don't know actually but I was afraid to delete it.

**Comment by bilelmoussaoui** [comment]
You don't need it, we just need the.po file, meson takes care of that when building the application and create a.mo file and install it under the proper directory

**Comment by ashraf2033** [comment]
OK I've deleted it

**Pull request merged**
