### PR TITLE
Fix segfault crashes

### PR DESCRIPTION
**Pull request by Alecaddd**
I started working on some needed improvements to fix those random segfault.
I found out that some methods were getting called 2 or 3 times per click from multiple sources, and some areas were duplicated, probably due to some leftover code.

I improved the code a bit, being sure methods are called only once, preventing most of those infinite loops causing a segfault.

Still, some crashes are occurring, but they're not always related to the Fill Model, as I've experienced crashes also when commenting that entire area, by simply quickly selecting the same shape, or quickly clicking between multiple shapes.

I will still work on this, but if you guys can load this PR and see if you can figure why the last segfault are happening, it'd be great.

Akira can't crash :smile:

### CODE REVIEW

**Comment by Alecaddd** [comment]
I think I fixed all the other crashes happening except for those related to the fill model.
Random segfaults were happening when setting the cursor on startup, and when quickly clicking on the empty canvas.

Onto figuring out why the fill model causes a crash when clearing the list of items.

**Comment by Alecaddd** [comment]
Done! This is fixed....I think.
Ready for a full review!

**Comment by Alecaddd** [comment]
Thanks for the review.
I commented the debug because I needed to print messages only for the sections I was debugger, and all the other stuff were making a lot of noise.
I prefer to keep it commented so we can enable only the messages we need instead of having a terminal filled with everything.
What do you think?

**Comment by albfan** [comment]
As they are debug, they should only be printed if `G_MESSAGES_DEBUG=all` is set. Let me check what's happening

**Pull request merged**
