### PR TITLE
CI: Init Travis + Flatpak builds

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
This adds the Dockerfile of akiraux/flatpak and a readme file of how to update it in the future. 

This will be merged once I add the Travis CI part of things.

### CODE REVIEW

**Comment by refi64** [comment]
FYI there are Docker images with the GNOME runtime and SDK already available at
`registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:3.32`.

**Comment by albfan** [comment]
@bilelmoussaoui I think is better to stick with GNOME images as @refi64 said.

https://gitlab.gnome.org/GNOME/gitg/blob/master/.gitlab-ci.yml#L10

about travis we just need to translate this:

https://gitlab.gnome.org/GNOME/gitg/blob/master/.gitlab-ci.yml#L22

**Comment by Alecaddd** [comment]
What's the status of this?
I don't know anything about docker so I completely rely on your @bilelmoussaoui and @albfan to decide if it's good to merge :smile:

**Comment by Alecaddd** [comment]
@bilelmoussaoui, any updates on this?

**Comment by Alecaddd** [comment]
@bilelmoussaoui, waiting for your feedback on this

**Comment by bilelmoussaoui** [comment]
·@Alecaddd I will keep this MR open for a while until we get a proper and working remote for nightlies on our server. We already build Akira for testing using houston, no need to duplicate that.

**Comment by bilelmoussaoui** [comment]
Replaced with a Github action in #207

**Pull request closed without merging**
