### PR TITLE
Linear and Radial Gradients feature on CanvasItems

### LINKED ISSUE #605: Create Linear and Radial Gradients
## Expected Behavior

One of the features in the Beta Wishlist is Gradients. I would like to work on adding it. I have already gotten a simple gradient working and will discuss my approach here.
If there are any changes to be made, please comment. If not, could any of the maintainers create a branch- like ```WIP-gradients``` for this feature?

The following are some functionality this feature must have.

#### User Stories

1. The user should be able to change the type of coloring used (simple, linear gradient, radial gradient).
2. The user should be able to change the color shades of gradients using stop colors.
3. The user should be able to change the direction in which the gradient flows using the direction line.
4. If the user changes from either of the gradients to a simple color, their previous color should be used.

### UI Changes

In the **ColorPicker** popover, add a dropdown menu. This menu will be created using **Gtk.ComboBoxText**.
The dropdown menu will contain 3 items
    1. Simple Color: this will represent a simple, plain color.
    2. Linear Gradient: this will represent a linear gradient.
    3. Radial Gradient: this will represent a radial gradient.
    
The user can select what kind of fill they want.

Other that the dropdown menu, a *direction line* will also be created. This line will determine the direction of gradients. This line will only be present if "Linear Gradient" or "Radial Gradient" Mode is chosen.

The user can then drag this line around to change the direction of gradient. This is similar to how most graphics software products use gradients.

This is what the popover looks like after adding the dropdown menu

dropdown menu

This is what the gradient looks like by default.

gradient_window

### Code Changes

- The dropdown menu will be created in **Akira.Layouts.Partials.FillItem**, inside the **Gtk.Popover**.
- The widget used for this is **Gtk.ComboBoxText**.
- To handle drawing gradients and the direction line, **Akira.Lib.Components.Gradient** will be used.
- When a new item is selected from this menu, it triggers a signal **changed**.
- The handler for this signal will change the **color** property in **Akira.Models.FillsItemModel**.
- This in turn changes the color property in **Akira.Lib.Components.Fill**.
- In **Akira.Lib.Components.Fill**, a **Akira.Lib.Components.Gradient** object is used to draw a linear or radial gradient *Pattern* using the **Cairo** library.

This approach looks a little too complicated to me, but when the user changes the color of a **CanvasItem**, these are the steps that happen, which is why I did the same.

I have implemented this, and can be found on [my fork in the branch WIP-Gradient](https://github.com/AshishS-1123/Akira/tree/WIP-Gradients).

As of now, when the user selects the *Linear Gradient* or *Radial Gradient* mode, a static gradient of colors black and white and running diagonally appears. Its color or direction cannot be changed. The direction line also isn't created. But selecting another mode removes the gradient.

### Future Work

Implement the remaining User Stories. There are also some bugs that cause the CanvasItem to draw Simple colors even when gradient mode is selected.

### PR DESCRIPTION
**Pull request by AshishS-1123**
### UI Changes
1. The ColorPicker shows 3 buttons on top for **Solid Color**, **Linear Gradient** and **Radial Gradient**. The buttons show icons based on their coloring mode.
2. Below these buttons, a ```Gtk.EventBox``` is used to place stop colors on the gradients. It only becomes active in **Linear Gradient** or **Radial Gradient** mode.
3. The stop colors can be moved around by clicking on them. Moving the stop colors changes the background color of ```EventBox``` and the selected CanvasItem instantaneously. 
4. StopColors can be deleted by selecting them and pressing the delete button beside the ```Gtk.EventBox```.
5. In order to change the direction of the gradient, 2 nobs are present inside the selected canvas item. 
6. Dragging these nobs changes the gradient direction and automatically updates the shading.

### Code Changes
1. Added icons for ColorMode buttons.
2. Created ColorMode class as a container for Color Mode buttons and the EventBox.
3. Created GradientEditor class for adding new StopColors and modifying their colors.(The class for StopColor is implemented inside GradientEditor).
4. Created DirectionLine class for changing the direction of gradients. Uses circular nobs with button events to drag them around.

## Steps to Test
1. Create a CanvasItem which has a Fill object(like Rectangle or Ellipse)
2. Press the ColorButton in the Fill object. This opens a popover.
3. Click on either of the gradient buttons(2nd for Linear and 3rd for Radial).
4. In the rectangular box that appears below the buttons, add new stop colors by clicking on the horizontal line.
5. With a stop color selected(selected stop color is blue in color), change the color using the color picker below.
6. Click and drag the stop color to change their position.
7. Select some stop color and press the delete button to remove it. (Note that the first and last stop colors cannot be deleted).
8. After you are done playing with the stop colors, click somewhere on the screen to remove the popover.
9. By default, the nobs for gradient direction are present on the diagonal of the canvas item. Drag them to change the direction of the gradient.

## Screenshots 

stop_color_shot
direction_line shot

## Known Issues / Things To Do
1. Gradients haven't been implemented for Borders.
2. Minor bug-
    Select an item, then apply gradient to it and change the direction,
    Then select the item again and select gradient. The direction resets to its initial position.
    Fix: Use the gradient pattern from ColorModel to figure out the initial positions of gradient.
3. Gradients cannot be blended with gradients or colors.
4. Major bug- The app crashes when you do the following
    Select an item and apply gradient to it.
    Delete the fill item and create a new fill item.
    Selecting gradient mode in this fill item crashes the app.

## This PR fixes/implements the following **bugs/features**:
 

- Fixes #605

### CODE REVIEW

**Comment by Abdallah-Moh** [comment]
@AshishS-1123 Could you center the color options

**Comment by Alecaddd** [comment]
> @AshishS-1123 Could you center the color options

No, don't center them.

Thank you so much for this initial PR. I'll take some time to review it and give you some detailed feedback for both code and UI.

**Comment by Alecaddd** [comment]
I finally had some time to look at this PR and it looks very promising.
Here's some general improvements I think are necessary.

- Each color fill type (flat, liner, radial) should have its own color picker, as well as a list of document saved gradients. I'm not asking to implement those now, but I think the we should right away implement those fill type as tabs switchers inside the popover, so we can later add custom options for each of those types.
- The color button should change to reflect the fill type selection.
- If the flat fill type is selected, we shouldn't show the space for the gradient nor the trash can.
- The trash can should be disabled if not stop point of the gradient is selected.
- The stop points shouldn't be cut at the edges of the gradient bar.
- The far left and right stop points should be draggable to fully control the gradient.
- When a stop point is selected, the color widget should update to show the color of the selected stop point.

There are other various things that could be improved, but I think this is enough for now :D 
Thanks again for working on this.

**Comment by Alecaddd** [comment]
Marking this as Draft since it needs more work.

**Comment by AshishS-1123** [comment]
> The color button should change to reflect the fill type selection.
> If the flat fill type is selected, we shouldn't show the space for the gradient nor the trash can.
> The trash can should be disabled if no stop point of the gradient is selected.
> When a stop point is selected, the color widget should update to show the color of the selected stop point.

All of these have been implemented.

> The stop points shouldn't be cut at the edges of the gradient bar.

@Alecaddd I don't understand what you mean by this. I have used Adobe XD, and they seem to be placing the first and last stop colors at the corners. Since these stop points are centered at the edges of the GradientEditor, half side of them would have to be hidden. 
I could make then visible, but would have to sacrifice some of the width of the editor.

> The far left and right stop points should be draggable to fully control the gradient.

Dragging the first and last stop colors will reduce the space available for the user to add more stop colors in between them. Instead the user should move the nobs of direction line

Some of the additional features implemented are-

1. Allow user to move direction line with the color picker open. But if the user clicks anywhere other than the start and end nobs, the popup closes.
2. When the user deselects an item and again selects it, the previously set gradient value is loaded. (i.e. the gradient doesn't go to the default colors and direction)

If everything else is okay, should I mark this as *Ready for review*.

**Comment by Alecaddd** [comment]
This is getting better and better, thanks.
I'll have a full review tomorrow with a couple of changes before we can set it ready for a full review.
Great work!

**Comment by mbfraga** [comment]
Awesome stuff! Will review as soon as I have time :)

**Comment by Alecaddd** [comment]
Closing this since we're targeting the `main` branch with a completely different code base.

**Pull request closed without merging**
