### PR TITLE
CI: use flatpak github action

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
This uses https://github.com/bilelmoussaoui/flatpak-github-actions/ to build the flatpak & provides us with a per commit/PR artifact to make testing PR's much easier for users/contributors

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
I guess we need a newer vala than what we provide in the elementary base app

**Comment by albfan** [comment]
https://github.com/akiraux/Akira/pull/453/checks?check_run_id=1287607815#step:4:949

can we add some commands to see the vala version and the supposed vapis it contains?

**Comment by bilelmoussaoui** [comment]
@albfan That's vala 0.40.11 (that what was shipped last time I updated it on elementary). I can bump that but I'm afraid of breaking everything:)

**Comment by albfan** [comment]
No no. I mean, we have CONDITIONAL compilation, so it should compile.

Is based on this package? https://packages.ubuntu.com/bionic-updates/libvala-0.40-0 so this are the vapis included https://packages.ubuntu.com/bionic-updates/valac-0.40-vapi?

**Comment by bilelmoussaoui** [comment]
No it's not based on any debian package out there. It's vala built from source https://github.com/flathub/io.elementary.BaseApp/blob/branch/juno-20.08/io.elementary.BaseApp.yml#L48

**Comment by Alecaddd** [comment]
I see you removed the `elementary/docker:unstable` build source.
Is it possible to keep it in order to maintain the build testing of the elementary app?
Elementary is transition to Flatpak as well, but till then we still need to support elementary OS 5 and its build system.

**Comment by bilelmoussaoui** [comment]
> I see you removed the `elementary/docker:unstable` build source.
> Is it possible to keep it in order to maintain the build testing of the elementary app?
> Elementary is transition to Flatpak as well, but till then we still need to support elementary OS 5 and its build system.

Done, this should be ready to go =)

**Comment by Alecaddd** [comment]
@albfan @bilelmoussaoui what's the status of this?
I don't know anything about Flatpak so I trust you guys.

**Review by albfan — APPROVED** [review]
@bilelmoussaoui is this maintainer of flatpak github action so we can trust him blindy on this changes.

**Pull request merged**
