### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:-)

### CODE REVIEW

**Comment by Alecaddd** [comment]
@XP312 would you be available to review the strings?
No one in the team speaks German :sweat_smile:

**Comment by Vistaus** [comment]
Dutch and German are similar, but not that similar that we can review each other's strings.

**Comment by XP312** [comment]
Thats funny @Alecaddd you probably things this because "German" means in Germany "Deutsch" :)

**Comment by Alecaddd** [comment]
Oh man, I'm to worst >_>
Sorry for the ignorant assumption

**Pull request merged**
