### PR TITLE
Minor updates to README.md

### PR DESCRIPTION
**Pull request by anselm94**
* Added Dependency installation instructions for Debian based OSes (Elementary/Ubuntu etc.)
* Minor updates to formatting
* Linked COPYING file to License section

### CODE REVIEW

**Comment by albfan** [comment]
dependency can be a section for wiki. But that's too distro specific.

**Comment by anselm94** [comment]
I was of the impression that the UX design is geared towards Elementary OS, adding instructions for Elementary OS (and its debian sisters) will make sense. Still, anyone from Fedora/Arch can add respective sections

**Comment by albfan** [comment]
That info is expected to be seen on a wiki or in CONTRIBUTING.md (there's an open issue for that).

You can detail the dependencies somewhere, but maintain the package names (which can change from time to time) isn't helpful. I use to keep that specific info in a wiki FAQ: "How to I build in Debian?"

**Comment by Alecaddd** [comment]
@anselm94 I agree with Alberto.

Could you please update the PR to not include the specific packages?
The other updates are useful and I'd like to merge it.

Cheers

**Comment by anselm94** [comment]
Thanks for the feedback @albfan @Alecaddd 
Removed the distro specific instructions from README.md

**Pull request merged**
